### ISSUE TITLE
Querying connections: nodes, edges>nodes vs nothing

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm-graphql#28]
It seems there are 3 ways out there how you can query a field with multiple records (connections):

1) Via a `nodes` field (this is what the plugin does currently)

```graphql
users {
  count
  nodes {
    id
    email
    name
  }
}
```

2) Via a `node` field within a `edges` field

```graphql
users {
  count
  edges {
    node {
      id
      email
      name
    }
  }
}
```

3) Via none of these

```graphql
users {
  id
  email
  name
}
```

Due to the fact that some APIs support 1 and 2, some support only 2 and some only support 3, it makes the usage of this plugin difficult, due to the fact that we hard implemented case 1.

Maybe we should implement a cascading detection of how the query should look like based on the schema. The GraphQL Plugin could automatically detect whether `nodes` is supported or if not whether `edges > node` is supported and if not fallback to use neither of those.

Additionally there should be a options flag where you can enforce one of these modes.

However for me it's not clear what the standard way is and what makes sense, which is something we have to find out.

Thanks to @oligus for reporting!

**Comment by phortx** [comment]
I thought about that and I think the plugin should be as flexible as possible. That doesn't mean we will implement every guff of everyone, but when there is no clear standard and many different implementations, I think we should support that.

I will implement that in the next days.

**Comment by phortx** [comment]
https://github.com/vuex-orm/vuex-orm-graphql/pull/29

**Comment by phortx** [comment]
@oligus I've created a PR for that.

Could you test it if it works for you? You can simply checkout the branch, run `yarn link` within the Vuex-ORM-GraphQL directory and then run `yarn link @vuex-orm/plugin-graphql` in your project (you have to recompile your project).

In best case everything works out of the box. Otherwise you maybe have to pass `connectionQueryMode: 'plain'` to the options.

I'm looking forward to hear your feedback :)

Thanks for your help!

**Comment by oligus** [comment]
@phortx 

I did try this but unfortunately I ran into an error for a normal list type:

![screenshot from 2018-06-20 15-10-49](https://user-images.githubusercontent.com/2466591/41660416-4041527c-749c-11e8-8dfd-4d68f5f7b27a.png)

It might be the way we implement GraphQL, but as I understand it `name` should be included in the type?

Thanks!

**Comment by phortx** [comment]
No, that's ok. The LIST Type has no name. I will take a look  :)

**Comment by phortx** [comment]
I pushed a fix. Could you try again? :)

**Comment by phortx** [comment]
Also I deployed the documentation: https://vuex-orm.github.io/vuex-orm-graphql/guide/connection-mode/

**Comment by oligus** [comment]
Thanks it works now both in `plain` and `nodes` mode. The auto detection doesn't seem to work for either.

Also, the error message contains spelling error:
`Error: Can't determine the connection mode due to the fact that here are no connection types in the schema. Please set the connecitonQueryMode via Vuex-ORM-GraphQL options`

`connecitonQueryMode` should be `connectionQueryMode`

Thanks again!

**Comment by phortx** [comment]
Pity. However this may be related how the GraphQL Schema reacts to the introspection query.

Thanks for the testing and the advice. I think this is a good base we can start with :)

**Comment by phortx** [comment]
Merged and released [v1.0.0-rc.8](https://github.com/vuex-orm/vuex-orm-graphql/releases/tag/v1.0.0-rc.8)

**Comment by creaux** [comment]
From documentation is not clear where to configure this.

**Comment by creaux** [comment]
Sorted https://github.com/vuex-orm/plugin-graphql/issues/106#issuecomment-500312935 -> https://vuex-orm.github.io/plugin-graphql/guide/adapters.html
