### ISSUE TITLE
Add version and linked state as debug logging

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm-graphql#34]
It would be nice when the plugin could print the version and whether it's linked or not. Like: `[Vuex-ORM-GraphQL] Version 1.0.0-rc.8 (linked from /Users/superman/projects/vuex-orm-graphql)`

Not sure if it's possible to determine whether the project is linked.

**Comment by kiaking** [comment]
Adding version is easy by importing `package.json` but I think linking is very hard, since the plugin runs on browser, there's no way to check local machines file system... :/

**Comment by phortx** [comment]
Thanks for the info!

I fear you're right, I could find a way either. Thanks for your help! :)

**Comment by phortx** [comment]
Even printing the version is not that simple because of the different compilation steps this plugins runs through.

It's not worth to add another npm package or investing to much time on this nice-to-have feature.

/cloase
